# Form implementation generated from reading ui file 'c:\Users\nickm\OneDrive\Desktop\Lobby_gui\lobby_guii.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1201, 791)
        self.lobby_gui = QtWidgets.QWidget(Dialog)
        self.lobby_gui.setGeometry(QtCore.QRect(0, 0, 1201, 800))
        self.lobby_gui.setMinimumSize(QtCore.QSize(1201, 0))
        self.lobby_gui.setAutoFillBackground(False)
        self.lobby_gui.setStyleSheet("QWidget#lobby_gui{\n"
"background-color: rgb(136,136,136);\n"
"}")
        self.lobby_gui.setObjectName("lobby_gui")
        self.players_label = QtWidgets.QLabel(self.lobby_gui)
        self.players_label.setGeometry(QtCore.QRect(260, 80, 431, 71))
        self.players_label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.players_label.setObjectName("players_label")
        self.error = QtWidgets.QLabel(self.lobby_gui)
        self.error.setGeometry(QtCore.QRect(440, 456, 341, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.players_list_widget = QtWidgets.QListWidget(self.lobby_gui)
        self.players_list_widget.setGeometry(QtCore.QRect(90, 170, 771, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.players_list_widget.sizePolicy().hasHeightForWidth())
        self.players_list_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.players_list_widget.setFont(font)
        self.players_list_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.players_list_widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.players_list_widget.setAutoFillBackground(True)
        self.players_list_widget.setStyleSheet("QListWidget {\n"
"    background-color: rgb(136,136,136);\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: #6495EDf;\n"
"    border-bottom: 1px solid #d0d0d0;\n"
"    padding: 5px 0;\n"
"    color: white;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #b7d7ff;\n"
"    color: black;\n"
"}")
        self.players_list_widget.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.players_list_widget.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.players_list_widget.setObjectName("players_list_widget")
        self.disbutton = QtWidgets.QPushButton(self.lobby_gui)
        self.disbutton.setGeometry(QtCore.QRect(870, 660, 261, 61))
        self.disbutton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(176, 196, 222);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.disbutton.setObjectName("disbutton")
        self.find_match_button = QtWidgets.QPushButton(self.lobby_gui)
        self.find_match_button.setGeometry(QtCore.QRect(870, 580, 261, 61))
        self.find_match_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(176, 196, 222);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.find_match_button.setObjectName("find_match_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.players_label.setText(_translate("Dialog", "Spieler-Online:"))
        self.disbutton.setText(_translate("Dialog", "Disconnect"))
        self.find_match_button.setText(_translate("Dialog", "Spiel suchen"))
